baseURL = "/"
languageCode = "en-us"
title = "$ goroutine dreams"

theme = "goroutine-dreams-theme"
paginate = 5
pygmentsStyle = "solarized-dark" # solarized-light, -dark or -dark256

[params]
  scheme = "light" # light, dark or gray
  description = "From the desk of a bright-eyed developer: An obligatory tech blog about the Go programming language"

[menu]
  [[menu.main]]
    name = "All Posts"
    url = "/"
  [[menu.main]]
    name = "Feed"
    url = "/index.xml"
  [[menu.main]]
    name = "Repository"
    url = "https://github.com/bake/solar-theme-hugo"
  [[menu.other]]
    name = "Hugo"
    url = "https://themes.gohugo.io/solar-theme-hugo/"
  [[menu.other]]
    name = "Demo"
    url = "https://themes.gohugo.io/theme/solar-theme-hugo/"